/**
 * Emoji → Lottie file id, generated by `scripts/fetch-animations.mjs`.
 * DO NOT EDIT BY HAND — re-run the script instead.
 *
 * Animations are Google's Noto Animated Emoji, licensed CC BY 4.0.
 * Files live in `public/anim/<id>.json` and are fetched on demand.
 * Emoji with no upstream animation are simply absent here, and the UI
 * falls back to the static glyph.
 */
export const animatedEmoji: Record<string, string> = {
  '⏳': '23f3',
  '⚠️': '26a0_fe0f',
  '⚡': '26a1',
  '✏️': '270f_fe0f',
  '⭐': '2b50',
  '🌀': '1f300',
  '🌈': '1f308',
  '🌟': '1f31f',
  '🌡️': '1f321_fe0f',
  '🎭': '1f3ad',
  '🏠': '1f3e0',
  '👃': '1f443',
  '👋': '1f44b',
  '💗': '1f497',
  '💛': '1f49b',
  '💡': '1f4a1',
  '💧': '1f4a7',
  '💪': '1f4aa',
  '💬': '1f4ac',
  '📷': '1f4f7',
  '🔒': '1f512',
  '🖨️': '1f5a8_fe0f',
  '🗣️': '1f5e3_fe0f',
  '😀': '1f600',
  '😊': '1f60a',
  '😌': '1f60c',
  '😕': '1f615',
  '😮‍💨': '1f62e_200d_1f4a8',
  '😵‍💫': '1f635_200d_1f4ab',
  '🙂': '1f642',
  '🙌': '1f64c',
  '🙏': '1f64f',
  '🤕': '1f915',
  '🤫': '1f92b',
  '🦴': '1f9b4',
  '🦿': '1f9bf',
  '🩸': '1fa78',
  '🩺': '1fa7a',
}

export function animationUrl(emoji: string): string | null {
  const id = animatedEmoji[emoji]
  return id ? `anim/${id}.json` : null
}
